project_id = "togplvyjetfapnpgcxza"

[functions.generate-quote]
verify_jwt = true

[functions.analyze-cad]
verify_jwt = true

[functions.analyze-pdf]
verify_jwt = true

[functions.update-commodity-prices]
verify_jwt = false
