// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// HARDCODED: Override Lovable's Supabase integration
const SUPABASE_URL = "https://togplvyjetfapnpgcxza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvZ3BsdnlqZXRmYXBucGdjeHphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3Mjk1NTUsImV4cCI6MjA3NjMwNTU1NX0.oXUHs1K5U5QM_a1pZvsoXgfYzb8Lsegah7nbi00rhwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});